apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: registercitizen
  namespace: dapr-asha
spec:
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://localhost:1883
  - name: topic
    value: asha/registercitizen
  - name: consumerID
    value: "{uuid}"
scopes:
  - ashaservice
  - anmservice